---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  # - name: ubuntu-14.04
  # - name: centos-7.1
  - name: centos-5
    driver_config:
      image: centos:5.11
      platform: centos

suites:
  - name: default
    run_list:
      - recipe[audit-shell-shock::default]
    attributes:
